### ISSUE TITLE
[BUG] [ws-tool-name] Issue Short Description

### ISSUE THREAD

**Issue by NatalyaDalid** [whitesource-ps/ws-ignore-alerts#45]
Hi @uandrei ,
I want to update you that the fix for copying comments for REJECTED_BY_POLICY_RESOURCE type has been solved.
Please let us know if it works as expected. 

Thanks,
Mend PS Team

**Comment by uandrei** [comment]
Hi @NatalyaDalid.

I've just tested version 0.2.4 of the ws_ignore_alerts script and the policy violations messages are still not copied across.

Here's a snapshot of the error message i can see in the Policy Violations screen once the ignore alerts utility has been run.
![image](https://user-images.githubusercontent.com/11975434/182130006-bf18c94a-91f5-47e0-8743-1ed027e0769a.png)

Were you expecting this to work automatically?

Cheers,
Andrei

**Comment by NatalyaDalid** [comment]
Hi @uandrei ,

It's really strange. You can see on my print screen that it works in my test. 
The only thing I can think about is that I wrote you it was ready before it had been in Production. Could you please retest it and let me know?
![image](https://user-images.githubusercontent.com/63256867/183284397-32b06609-4389-4efc-a71d-d5cf7e406a19.png)

Natalya

**Comment by uandrei** [comment]
Hi @NatalyaDalid,

Yes, it seems to be working OK now.

Thanks,
Andrei
